// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDD0xKIqgSp-rxnfVBG00cUTNxaUlCPuAs",
      authDomain: "vt-partner-4a2b1.firebaseapp.com",
      projectId: "vt-partner-4a2b1",
      storageBucket: "vt-partner-4a2b1.firebasestorage.app",
      messagingSenderId: "1046135317601",
      appId: "1:1046135317601:web:d67f42c5990b18bfe07620",
      measurementId: "G-88M7BTM15M");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ7ttzeTq4_yjghsU_I8ObU_sj28tLbME',
    appId: '1:590399228771:android:a6b4af235586a0925fe156',
    messagingSenderId: '590399228771',
    projectId: 'vt-partner-8317b',
    storageBucket: 'vt-partner-8317b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlwkhT4NPbMt-fwSEYui_mUDL8QlMfB28',
    appId: '1:590399228771:ios:baa1ce7a4246e2a05fe156',
    messagingSenderId: '590399228771',
    projectId: 'vt-partner-8317b',
    storageBucket: 'vt-partner-8317b.firebasestorage.app',
    iosBundleId: 'com.vtpartnertranspvtltd.vtPartner',
  );
}
